#!/usr/bin/env python
# coding: utf-8

# In[1]:


#1#Create a 1D numpy array with the integers 0-9
import numpy as np
l1 = [0,1,2,3,4,5,6,7,8,9]
arr1 = np.array(l1)
l1


# In[6]:


#2#Create a 2D numpy array with shape (3,3) and fill it with zeroes
l2 = [10,11,12,13,14,15,16,17,18,19]
arr2 = np.array(l2)
l = [l1,l2]
arr2 = np.array(l)
arr2.shape
np.zeros([3,3])


# In[8]:


#3#Create a 3D numpy array with shape (2,3,4) and fill it with ones
arr3 = np.ones([2,3,4])
arr3


# In[11]:


#4#Create a numpy array with 10 random integers between 0-100
arr4 = np.random.randint(0,100,10)
arr4


# In[12]:


#5#Create a numpy array with 10 random float between 0-1
arr5 = np.random.rand(10)
arr5


# In[16]:


#6#Create a numpy array with 5 equally spaced values between 0 and 1
arr6 = np.linspace(0,1,5) #using linespace start =0 , end = 1, num=5
arr6


# In[17]:


#7#Create a numpy array with 5 equally spaced values between 0 and 10
arr7 = np.linspace(0,10,5) #using linespace start =0 , end = 10 num=5
arr7


# In[18]:


#8#Create a numpy array with 5 equally spaced values between -1 and 1
arr8 = np.linspace(-1,1,5) #using linespace start =0 , end = 10 num=5
arr8


# In[34]:


#9#Create a numpy array with the sine values of angles between 0 and 2pi
arr9 = np.sin(np.arange(0,361,90)*2*np.pi/180)
arr9


# In[33]:


#10#Create a numpy array with the cosine values of angles between 0 and pi
arr10 = np.cos(np.arange(0,361,90)*np.pi/180)
arr10


# In[ ]:





