#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np


# In[2]:


arr1 = np.array([[1,2,3,4],[8,9,10,11]])
print("The 2D Array is:\n",arr1)


# In[3]:


print("The product of the array multiplcation:\n",arr1*arr1)


# In[4]:


print("The aray after applying -2 scaler:\n",arr1-2)


# In[5]:


print("The product of the array to the power of 3:\n",arr1**3)


# In[7]:


A=np.array([[1,2,3],[4,5,6]])
print("The first 2D Array:\n",A)
B=np.array([[7,8],[9,10],[11,12]])
print("The Second 2D Array:\n",B)
print("The dot product of the matrices = \n",np.dot(A,B))


# In[ ]:





